### PR TITLE
fixing bug related to Issue #457

### PR DESCRIPTION
**Pull request by sachin-shrestha**
What type of PR is this?
/kind bug

What this PR does / why we need it:
ObjectType.schema.json is missing the enum TX_ISSUER_AUTHORIZED_SHARES_ADJUSTMENT, resulting in a failure when validating sample data.
IssuerTransaction.schema.json references required field stock_class_id when it's not in the properties, should be issuer_id

### CODE REVIEW

**Comment by sachin-shrestha** [comment]
@JSv4 or @pjohnmeyer ...can one of you review please?

**Comment by JSv4** [comment]
On it @sachin-shrestha

**Comment by JSv4** [comment]
Thanks, @sachin-shrestha, this all looks good to me. Is this something you need merged? If not, I'd like to revisit our versioning tomorrow. We wanted to more formally document that for a while. Since this would technically be a breaking change - even though it fixes a bug - I want to make sure we either (a) version up as appropriate or (b) have a sane and documented policy for the versioning. @pjohnmeyer, would love your thoughts on this. 

FYI, I also opened a new issue #470 to add some structural validation checks to catch both of the issues you fixed here. There's no reason they should have made it through the test suite.

**Comment by JSv4** [comment]
Let's also have a sample here too in the sample transactions file.

**Comment by jacobyavis** [comment]
Added samples, and the description looked okay but I made a minor change

**Comment by pjohnmeyer** [comment]
> Since this would technically be a breaking change - even though it fixes a bug

Just noting for posterity that this was not a breaking change because this object did not exist in v1.1.0.

**Pull request merged**
