### PR TITLE
add volta to package.json and add .gitattributes

### PR DESCRIPTION
**Pull request by MattCantor**
#### What type of PR is this?

cleanup

#### Which issue(s) this PR fixes:

Couple of things to help folks like me stuck on a corporate windows machine without user privileges:

**Volta**
[Volta](https://volta.sh/) is a nice way to manage node instances.  Also I think it plays nicely with (ie ignores) the .node-version file nvm relies on.

**.gitattributes**
`text=auto` and `eol-crlf` should help avoid me unintentionally committing a bunch of unintentional changes around line endings?

Fixes #

N/A

### CODE REVIEW

**Comment by MattCantor** [comment]
Need to update pre-commit hook to conform to changes to .node-version

**Comment by osis** [comment]
Cool! Never heard of volta but now I know! Any particular reason why you'd use this over `nvm`?

**Comment by MattCantor** [comment]
> Cool! Never heard of volta but now I know! Any particular reason why you'd use this over `nvm`?

nvm requires admin privileges on my corporate windows machine

**Comment by arthur-clara** [comment]
Agreed to park this for now.

**Pull request closed without merging**
