### PR TITLE
add PROJECTS.md and link to it from README.md

### LINKED ISSUE #361: [Enhancement]: Start tracking ongoing projects "awesome-ocf"
### Description of Enhancement :

Add a file just to track any ongoing projects related to OCF.

### Why is this Needed?

Summary of the ecosystem can convince people to adopt OCF and prevent duplicate work efforts.

### PR DESCRIPTION
**Pull request by dan-pulley**
#### What type of PR is this?
/kind documentation

#### Which issue(s) this PR fixes:
Fixes #361 

image

### CODE REVIEW

**Comment by dan-pulley** [comment]
looks good in OCF meeting

**Comment by JSv4** [comment]
@dan-pulley, can you please rebase this off the latest main? There are a lot of file changes in this PR, and I want to be 100% sure I'm not missing something substantive outside of the new MD file.

**Review by JSv4 — CHANGES_REQUESTED** [review]
Please rebase off latest main

**Comment by jacobyavis** [comment]
@dan-pulley From TWG call March 21 2023: will you please rebase this branch and then we can get this merged? Thanks!

**Comment by JSv4** [comment]
@dan-pulley, please rebase so we can clear this pending PR. Thx

**Comment by dan-pulley** [comment]
@JSv4 good to go

**Review by JSv4 — APPROVED** [review]
Looks great, thanks! Made a couple changes to pull your md into the nav links and also add PyOCF.

**Pull request merged**
