### PR TITLE
Make schemas available

### LINKED ISSUE #248: [Enhancement]: Make Schemas Available at "opencaptablecoalition.com"
### Current Behavior:

Running the schemas through a JSON validator like Ajv, the schemas listed here are a bit broken. Many of the schemas reference `opencaptablecoalition.com` but they aren't actually present on that site. For instance, the `Address` references the `CountrySubdivisionCode` schema like this: 
```
      "$ref": "https://opencaptablecoalition.com/schema/types/CountrySubdivisionCode.schema.json"
```
but that URL is currently broken. This causes validators with external reference checking to fail.

### Expected Behavior:

`$ref` and `$id` fields in the schemas point to valid files.

### Steps to Reproduce:

Run a validator with external reference checking (like [Ajv](https://www.npmjs.com/package/ajv)) against a schema file with a reference.

### PR DESCRIPTION
**Pull request by xudiera**
#### What type of PR is this?

/kind enhancement

#### What this PR does / why we need it:

The ids and refs on the JSON schemas are referencing https://opencaptablecoalition.com but those urls are broken at the moment. This PR will change the reference to https://raw.githubusercontent.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF instead.

#### Which issue(s) this PR fixes:

Fixes #248

### CODE REVIEW

**Comment by xudiera** [comment]
TODO:

- [ ] Change ref properties
- [ ] Fix tests

**Comment by JSv4** [comment]
Thanks again for this, @xudiera. I worked through a huge PR and Issue backlog today. Will finally get to this in the first half of next week.

**Comment by JSv4** [comment]
@xudiera, oh, also, I see your comment. Do the existing tests not work after this? We'll need to make sure we can fix those before we can merge this.

**Comment by JSv4** [comment]
Hey @xudiera, can you please rebase this off the latest main branch and get the tests running again?

**Comment by JSv4** [comment]
Hey @xudiera, are you able to take a look at this this week? I'd like to include this as part of our stable release if you can make the necessary updates.

**Pull request closed without merging**
