### PR TITLE
Added scripts to run tests on Windows

### LINKED ISSUE #292: [Bug]: Running tests on Windows is not working
### Current Behavior:

Running tests on Windows is not working.

### Expected Behavior:

Running `npm run test` should work on Windows.

### Steps to Reproduce:

Run `npm run test` on Windows:

image

### Environment:

- OS: Windows 10
- Node: 16.13.1
- npm: 8.1.2

### PR DESCRIPTION
**Pull request by xudiera**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Running `npm run test` should work on Windows.

#### Which issue(s) this PR fixes:

Fixes #292 

#### See
https://jestjs.io/docs/troubleshooting
https://github.com/facebook/jest/issues/3750

### CODE REVIEW

**Comment by JSv4** [comment]
Hey @xudiera, I'm running node 16.13.1 this time, and I'm not able to run `npm run test`. I can run `npm run test:windows` successfully, but it'd be nice to just have a single test command that's platform agnostic. Is the behavior I'm seeing what you're seeing, or am I perhaps missing a package?

**Comment by JSv4** [comment]
Thanks for clarifying at the TWG meeting today, @xudiera. As discussed, can you please add a note in the README about the platform-specific npm command required for windows and open a "nice-to-have" issue to find a way to run the appropriate test based on the current platform? Thanks!

**Review by JSv4 — CHANGES_REQUESTED** [review]
@xudiera, can you please make the changes I suggested in my earlier comments? Then I can get this merged in. Thanks!

**Comment by xudiera** [comment]
@JSv4 the last commit I pushed makes the command platform independent. There is not need to add a note to the README neither do we need to create a new issue.

**Comment by JSv4** [comment]
> @JSv4 the last commit I pushed makes the command platform independent. There is not need to add a note to the README neither do we need to create a new issue.

Oh cool! My bad for missing that. Let me give that a spin and get it merged up.

**Review by JSv4 — APPROVED** [review]
Working for me on Windows 10 and Ubuntu 22.04

**Pull request merged**
