### PR TITLE
Hard-wrap Markdown files w/ Prettier

### PR DESCRIPTION
**Pull request by pjohnmeyer**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Changes the Prettier config to wrap prose to make our Markdown files more readable.

The default Prettier config is to wrap at 80 columns; I considered setting this to 100 and I am open to whatever the team wants.

#### Which issue(s) this PR fixes:
n/a

### CODE REVIEW

**Comment by pjohnmeyer** [comment]
This is a draft so we can merge in and re-format #487 after it is approved and merged.

**Comment by jacobyavis** [comment]
Looking through the changes I would +1 on bumping the count to 100 char (or even 120)

**Comment by osis** [comment]
Lots of people are moving away from 80 as a default. We set 120 as the standard. Always going to be a bit of a debate on these things thought.

You can also check out Linus' take on this subject 😂 https://lkml.org/lkml/2020/5/29/1038

**Comment by pjohnmeyer** [comment]
TWG Notes: No opposition to the idea.

I'm going to bump to 100 per the commentary above and mark as ready for review.

**Pull request merged**
