### PR TITLE
Add Option Repricing Event

### LINKED ISSUE #460: [Enhancement]: Add an Option Repricing Event
### Description of Enhancement :

The legal working group raised the need to reprice a subset of options (identified by ID). 

### Why is this Needed?

In practice, options are sometimes repriced, and we don't have an event type that lets us change the option exercise price and keep a clean history of when the price changed and why.

### Anything else we need to know?

Imagining we'd have four fields:

- equity_compensation_ids - list of ids for relevant equity compensation issuances. 
- effective_date - date the repricing is effective as of
- notes - we have this anyway, just calling it out
- new_exercise_price - new exercise price

### PR DESCRIPTION
**Pull request by JSv4**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

As discussed in #460, we need a way to reprice outstanding equity compensation (options). This adds a transaction to reprice specific options.  

#### Which issue(s) this PR fixes:

Fixes #460

### CODE REVIEW

**Comment by MattCantor** [comment]
I apologize for my lack of familiarity with the schema, but does this repricing transaction create a new stock option, or does it merely adjust the exercise price of the existing stock option?  A stock option repricing is treated as the grant of a new stock option for purposes of determining status as an ISO or NSO.  So in some instances it is helpful for a repricing to be treated as a new grant.

**Comment by JSv4** [comment]
@MattCantor is going to put together an initial write-up of what goes into the NSO / ISO determinations and propose a way to handle ISO/NSO splits.

**Comment by JSv4** [comment]
> @MattCantor is going to put together an initial write-up of what goes into the NSO / ISO determinations and propose a way to handle ISO/NSO splits.

Hey @MattCantor, any updates on the write-up here?

**Comment by jacobyavis** [comment]
TWG notes Sep 12 -- @JSv4 going to see if any more changes are needed to be able to merge this

**Comment by MattCantor** [comment]
> > @MattCantor is going to put together an initial write-up of what goes into the NSO / ISO determinations and propose a way to handle ISO/NSO splits.
> 
> Hey @MattCantor, any updates on the write-up here?

https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/issues/504#issuecomment-2181186561

**Comment by ryansdwilson** [comment]
Can I suggest that we consider making this a re-issuance with one of the things you can change being price. Often when a repricing event occurs there are also material changes to the grant including its expiry provisions. Currently there is no way to capture this other than cancelling the grant and issuing a new one. If we did this as a re-issue (which is technically what a repricing is) we could enable the user to update any of the parameters of the option in the same way you can reissue stock. We could borrow from this pattern.

**Comment by JSv4** [comment]
> Can I suggest that we consider making this a re-issuance with one of the things you can change being price. Often when a repricing event occurs there are also material changes to the grant including its expiry provisions. Currently there is no way to capture this other than cancelling the grant and issuing a new one. If we did this as a re-issue (which is technically what a repricing is) we could enable the user to update any of the parameters of the option in the same way you can reissue stock. We could borrow from this pattern.

Thanks @ryansdwilson, at least in the U.S., there are a couple ways to do this. You could technically amend the option agreement to change the exercise price, or you could cancel and re-issue with a newly priced option.

**Comment by JSv4** [comment]
> > > @MattCantor is going to put together an initial write-up of what goes into the NSO / ISO determinations and propose a way to handle ISO/NSO splits.
> > 
> > 
> > Hey @MattCantor, any updates on the write-up here?
> 
> [#504 (comment)](https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/issues/504#issuecomment-2181186561)

Hey @MattCantor, I think we decided we didn't need to make any changes here for ISO/NSO split, **but** do we need to explicitly document any state transition restrictions - e.g. an ISO is repriced, are there restrictions or changes required on the resulting option?

**Comment by MattCantor** [comment]
> > > > @MattCantor is going to put together an initial write-up of what goes into the NSO / ISO determinations and propose a way to handle ISO/NSO splits.
> > > 
> > > 
> > > Hey @MattCantor, any updates on the write-up here?
> > 
> > 
> > [#504 (comment)](https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF/issues/504#issuecomment-2181186561)
> 
> Hey @MattCantor, I think we decided we didn't need to make any changes here for ISO/NSO split, **but** do we need to explicitly document any state transition restrictions - e.g. an ISO is repriced, are there restrictions or changes required on the resulting option?

The ISO/NSO split calculator will take an array of the optionee's options as a parameter.  This will need to include options that have been repriced.  That should be pretty straightforward in the case where the repricing creates a new option.  In the case where repricing does not create a new option, we'll need a way to indicate that the option has been repriced and a way to access the details of that repricing (i.e., date, old  FMV at grant date, new FMV at grant date)

see issue #535 re: tracking FMV on grant date

**Comment by arthur-clara** [comment]
NO comments from Nov 21 meeting against merging

**Pull request merged**
